### ISSUE TITLE
Issue with java "-Djava.libray.path=. Lab1" compiling

### ISSUE THREAD

**Issue by Sof-Saos** [Sof-Saos/st0244-2023-1-lab1#1]
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no lab1 in java.library.path: /usr/java/packages/lib:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2444)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:848)
        at java.base/java.lang.System.loadLibrary(System.java:2047)
        at Lab1.<clinit>(Lab1.java:11)
```

**Comment by Sof-Saos** [comment]
There were several causes of this error:
1. The most important error was when compiling with the command `gcc -fPIC -I"$JAVA_HOME/include" -I"$JAVA_HOME/include/linux" -shared -o,` when creating the library, it had to be defined with the name lib before the name given to it in the java program.
2. In the c++ program the native function was being called wrongly, because it still had the old name of the first versions of the code.
